format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIPv4}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_IPV4_COMMANDS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FORWARD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: TCPIP_IPV4_FORWARD_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_IPV4_FORWARD_TABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_BOOLX5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipIPv4, value: 'false'}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_DEST_IF_NAME_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: eth0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_DEST_IF_NAME_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: wlan0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_DEST_IF_NAME_IDX2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: eth0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_DEST_IF_NAME_IDX3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: wlan0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_DEST_IF_NAME_IDX4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: wlan0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_GW_ADD_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 0.0.0.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_GW_ADD_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 0.0.0.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_GW_ADD_IDX4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 0.0.0.0}
  - type: Integer
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_METRIC_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_METRIC_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_ADD_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_ADD_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_ADD_IDX2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.1.11}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_ADD_IDX3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.25}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_ADD_IDX4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 192.168.100.35}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_MASK_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_MASK_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_MASK_IDX2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.255}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_MASK_IDX3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.255}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NET_MASK_IDX4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 255.255.255.255}
  - type: Menu
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NUMBERX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Menu
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_NUMBERX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_SRC_IF_NAME_IDX0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: wlan0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_SRC_IF_NAME_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: eth0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_SRC_IF_NAME_IDX2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: wlan0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_SRC_IF_NAME_IDX3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: eth0}
  - type: String
    attributes: {id: TCPIP_IPV4_FWD_ENTRY_SRC_IF_NAME_IDX4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: eth0}
- type: ElementPosition
  attributes: {x: '186', y: '81', id: tcpipIPv4}
