format_version: v1.0
type: UniqueComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '41'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_EVENT_ENABLE_SOF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x2312'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: CryptoAuth WFI32}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_VENDOR_ID_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x03eb'}
- type: ElementPosition
  attributes: {x: '82', y: '345', id: usb_device}
