format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIcmp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_ICMP_COMMAND_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_ICMP_ECHO_REQUEST_TIMEOUT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_ICMP_TASK_TICK_RATE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_STACK_MAX_CLIENT_ECHO_REQUESTS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '580', y: '20', id: tcpipIcmp}
